(require './src')
	browserify:    false
	clean:         true
	coffee:        true
	copy:          false
	documentation: false
	less:          false
	livereload:    false
	nodemon:       false
	tests:         false
	watch:         true
